# This is a configuration file for the Github Pages edition of a book by Chastity.
# This site is managed by Chastity White Rose, the Vegan Virgin.

title: Minimal Markdown for Authors
description: How to Write and Publish a Book Using Open Source Software
